ALTER TABLE "RouteStep"
ADD COLUMN "canvasX" DOUBLE PRECISION,
ADD COLUMN "canvasY" DOUBLE PRECISION,
ADD COLUMN "material" TEXT,
ADD COLUMN "quantity" DOUBLE PRECISION,
ADD COLUMN "unit" TEXT,
ADD COLUMN "comment" TEXT,
ADD COLUMN "components" JSONB NOT NULL DEFAULT '[]';
