import {useEffect,useState} from 'react';
import {productionApi as api} from './production-api';
import './analytics.css';
type Metrics={workSeconds:number;downtimeSeconds:number;plannedSeconds:number;missingPlan:number;stops:number;completed:number;tasks:number};
type Report={totals:Metrics;centers:(Metrics&{id:string;name:string;planKnown:boolean})[];employees:{id:string;name:string;workSeconds:number;averageSeconds:number;completed:number;tasks:number}[];availableCenters:{id:string;name:string}[];stops:{id:string;operationId:string;title:string;center:string;orderNumber:string;reason:string;startedAt:string;finishedAt:string|null;seconds:number;carried:boolean}[];problems:{averageResolutionSeconds:number;frequentCenters:{id:string;name:string;stops:number;downtimeSeconds:number}[];orders:{number:string;count:number;downtimeSeconds:number}[]};stopTotal:number;page:number;asOf:string};
const day=(date:Date)=>date.toISOString().slice(0,10);
const duration=(seconds:number)=>{const minutes=Math.floor(seconds/60);return `${Math.floor(minutes/60)} ч ${minutes%60} мин`;};
export function Analytics({onOpenTask}:{onOpenTask:(id:string)=>void}){
 const [from,setFrom]=useState(()=>day(new Date(Date.now()-29*86400000))),[to,setTo]=useState(()=>day(new Date())),[center,setCenter]=useState('');
 const [query,setQuery]=useState({from,to,center}),[page,setPage]=useState(1),[refresh,setRefresh]=useState(0),[report,setReport]=useState<Report|null>(null),[error,setError]=useState(''),[loading,setLoading]=useState(true);
 useEffect(()=>{let active=true;setLoading(true);setError('');const params=new URLSearchParams({from:query.from,to:query.to,page:String(page),...(query.center?{workCenterId:query.center}:{})});api<Report>(`/planner/analytics?${params}`).then(data=>{if(active)setReport(data);}).catch(e=>{if(active){setError(e.message);setReport(null);}}).finally(()=>{if(active)setLoading(false);});return()=>{active=false;};},[query,page,refresh]);
 function apply(){setPage(1);setQuery({from,to,center});setRefresh(v=>v+1);}
 return <div className="content analytics-page"><h2>Работа и остановки</h2>
  <form className="analytics-filters" onSubmit={e=>{e.preventDefault();apply();}}><label>С даты<input type="date" required value={from} onChange={e=>setFrom(e.target.value)}/></label><label>По дату<input type="date" required value={to} onChange={e=>setTo(e.target.value)}/></label><label>Участок отчёта<select value={center} onChange={e=>setCenter(e.target.value)}><option value="">Все участки</option>{report?.availableCenters.map(c=><option value={c.id} key={c.id}>{c.name}</option>)}</select></label><button className="primary" disabled={loading}>Показать отчёт</button></form>
  <p className="dispatcher-note">Даты включительно, по UTC; максимум 366 дней. Учитывается только время внутри периода, по момент последнего расчёта. Архивные заказы включены в историю.</p>{error&&<p className="error" role="alert">{error}</p>}{loading?<p>Расчёт отчёта…</p>:report&&<>
   <section className="analytics-metrics"><article><span>Время работы</span><strong>{duration(report.totals.workSeconds)}</strong></article><article><span>План</span><strong>{report.totals.missingPlan?`Неполный: ${report.totals.missingPlan}`:duration(report.totals.plannedSeconds)}</strong></article><article><span>Простой</span><strong>{duration(report.totals.downtimeSeconds)}</strong></article><article><span>Новые остановки</span><strong>{report.totals.stops}</strong></article><article><span>Среднее устранение</span><strong>{report.problems.averageResolutionSeconds?duration(report.problems.averageResolutionSeconds):'—'}</strong></article><article><span>Завершено задач</span><strong>{report.totals.completed}</strong></article></section>
   <h3>План / факт по участкам</h3><div className="analytics-table"><table><thead><tr><th>Участок</th><th>План</th><th>Факт</th><th>Простой</th><th>Новые остановки</th><th>Завершено</th></tr></thead><tbody>{report.centers.map(row=><tr key={row.id}><td><button className="secondary" onClick={()=>{setCenter(row.id);setQuery(q=>({...q,center:row.id}));setPage(1);}}>{row.name}</button></td><td>{row.planKnown?duration(row.plannedSeconds):'Норматив не задан'}</td><td>{duration(row.workSeconds)}</td><td>{duration(row.downtimeSeconds)}</td><td>{row.stops}</td><td>{row.completed}</td></tr>)}</tbody></table></div>{!report.centers.length&&<p>За выбранный период нет зарегистрированной работы и событий.</p>}
   <h3>Производительность сотрудников</h3><div className="analytics-table"><table><thead><tr><th>Сотрудник</th><th>Работа</th><th>Задач</th><th>Завершено</th><th>Среднее время</th></tr></thead><tbody>{report.employees.map(employee=><tr key={employee.id}><td>{employee.name}</td><td>{duration(employee.workSeconds)}</td><td>{employee.tasks}</td><td>{employee.completed}</td><td>{duration(employee.averageSeconds)}</td></tr>)}</tbody></table></div>{!report.employees.length&&<p>В выбранном периоде нет записанных интервалов с сотрудниками.</p>}
   <h3>Остановки и причины</h3><p className="dispatcher-note">В списке есть и остановки, начавшиеся раньше периода. Они увеличивают время простоя, но не число новых остановок.</p>{report.stops.map(stop=><button className="analytics-stop" key={stop.id} onClick={()=>onOpenTask(stop.operationId)}><strong>{stop.center} · Заказ № {stop.orderNumber}</strong><span>{stop.title}</span><span>{stop.reason}</span><small>Начало: {new Date(stop.startedAt).toLocaleString('ru-RU',{timeZone:'UTC'})} UTC · {stop.finishedAt?`завершение: ${new Date(stop.finishedAt).toLocaleString('ru-RU',{timeZone:'UTC'})} UTC`:'Не завершена к концу расчётного периода'}{stop.carried?' · началась до выбранного периода':''}</small><b>Простой в периоде: {duration(stop.seconds)}</b></button>)}{!report.stops.length&&<p>Остановок в выбранном периоде нет.</p>}
   <section className="analytics-problems"><div><h3>Чаще останавливались</h3>{report.problems.frequentCenters.length?report.problems.frequentCenters.map(row=><p key={row.id}><b>{row.name}</b><span>{row.stops} остановок · {duration(row.downtimeSeconds)}</span></p>):<p>Новых остановок нет.</p>}</div><div><h3>Заказы с проблемами</h3>{report.problems.orders.length?report.problems.orders.map(row=><p key={row.number}><b>Заказ № {row.number}</b><span>{row.count} остановок · {duration(row.downtimeSeconds)}</span></p>):<p>Новых остановок нет.</p>}</div></section>
   <div className="pagination"><button className="secondary" disabled={page===1} onClick={()=>setPage(p=>p-1)}>Предыдущие остановки</button><span>Страница {page} из {Math.max(1,Math.ceil(report.stopTotal/30))}</span><button className="secondary" disabled={page*30>=report.stopTotal} onClick={()=>setPage(p=>p+1)}>Следующие остановки</button></div><small>Рассчитано: {new Date(report.asOf).toLocaleString('ru-RU')}</small>
  </>}</div>;
}
