import {ForecastAttention} from "./forecast-attention";
import {OrderForecast} from "./order-forecast";
import {useEffect,useState} from 'react';
import {productionApi as api,useProductionEvents} from './production-api';
import {OperationsScreen,Notifications} from './operations';
import './dashboard.css';
type Group={count:number;amount:number;orders:{id:string;number:string;dueDate:string|null;amount:number}[]};
type Report={groups:Record<string,Group>;stopped:number;unread:number;asOf:string};
const labels:Record<string,string>={procurement:'В закупке',ready:'Готово к запуску',production:'В производстве',completed:'Готовая продукция',unplanned:'Не запущено',overdue:'Просрочено'};
const money=(value:number)=>value.toLocaleString('ru-RU',{style:'currency',currency:'RUB',maximumFractionDigits:2});
export function Dashboard({onOpenTask}:{onOpenTask:(id:string)=>void}){
  const [report,setReport]=useState<Report|null>(null),[filter,setFilter]=useState('production'),[error,setError]=useState(''),[refresh,setRefresh]=useState(0),[order,setOrder]=useState<{id:string;productionOrderNumber:string;items:{id:string;name:string;quantity:number;unitPrice:number;completedQuantity:number}[]}|null>(null);
  const revision=useProductionEvents();
  useEffect(()=>{let active=true;api<Report>('/planner/dashboard').then(data=>{if(active){setReport(data);setError('');}}).catch(e=>{if(active)setError(e.message);});return()=>{active=false;};},[revision,refresh]);
  async function openOrder(id:string){try{setOrder(await api(`/orders/${id}`));}catch(e){setError(e instanceof Error?e.message:'Ошибка загрузки заказа');}}
  return <div className="content dispatcher"><div className="page-actions"><div><p className="kicker">ДИСПЕТЧЕРСКАЯ ПЛАНЕРА</p><h2>Состояние производства</h2></div><button className="secondary" onClick={()=>setRefresh(v=>v+1)}>Обновить</button></div>{error&&<p className="error" role="alert">{error}</p>}{!report?<p>Загрузка показателей…</p>:<><section className="dispatcher-metrics">{Object.entries(labels).map(([key,label])=><button key={key} className={`${filter===key?'selected':''} ${key==='overdue'?'danger':''}`} onClick={()=>setFilter(key)}><span>{label}</span><strong>{report.groups[key].count} заказов</strong><b>{money(report.groups[key].amount)}</b></button>)}<button className={filter==='stopped'?'selected danger':'danger'} onClick={()=>setFilter('stopped')}><span>Остановлено</span><strong>{report.stopped} задач</strong><b>Причины и время простоя</b></button><button className={filter==='problems'?'selected':''} onClick={()=>setFilter('problems')}><span>Уведомления</span><strong>{report.unread} непрочитанных</strong><b>Открыть проблемы</b></button></section><ForecastAttention revision={revision} refresh={refresh} onOpen={id=>void openOrder(id)}/><p className="dispatcher-note">Суммы распределены по количеству позиций: готовая часть учитывается отдельно от находящейся в работе. Просрочка — дополнительная выборка незавершённой части. Один заказ может присутствовать на нескольких стадиях.</p><p className="dispatcher-note">Прогноз отдельных этапов доступен в карточках задач после ввода нормативов. Общий прогноз доступен при открытии заказа.</p>{filter==='stopped'?<OperationsScreen planner initialStatus="PAUSED"/>:filter==='problems'?<Notifications onOpen={onOpenTask}/>:<section className="panel dispatcher-orders"><h3>{labels[filter]}</h3>{!report.groups[filter].orders.length?<p>В этой выборке заказов нет</p>:report.groups[filter].orders.map(row=><button key={row.id} onClick={()=>void openOrder(row.id)}><strong>Производство № {row.number}</strong><span>{row.dueDate?`Срок: ${new Date(row.dueDate).toLocaleDateString('ru-RU')}`:'Срок не задан'}</span><b>{money(row.amount)}</b></button>)}{report.groups[filter].count>100&&<p>Показаны первые 100 заказов по ближайшему сроку.</p>}</section>}</>}{order&&<div className="modal-backdrop"><section className="task-dialog" role="dialog" aria-modal="true" aria-label="Позиции заказа"><header><h2>Заказ № {order.productionOrderNumber}</h2><button aria-label="Закрыть заказ" onClick={()=>setOrder(null)}>×</button></header>{order.items.map(item=><div key={item.id} className="dispatcher-item"><b>{item.name}</b><span>{item.quantity} шт. · готово {item.completedQuantity} шт.</span><span>{money(item.quantity*item.unitPrice)}</span></div>)}<OrderForecast id={order.id}/></section></div>}</div>;
}
