import {useEffect,useState} from 'react';
import {productionApi as api} from './production-api';
type Filter='RISK'|'LATE'|'DATA';
type Report={counts:Record<Filter,{count:number;amount:number}>;items:{id:string;number:string;dueDate:string|null;finish:string|null;reserveHours:number|null;amount:number;reason:string}[];total:number;page:number;asOf:string};
const labels:Record<Filter,string>={RISK:'Под риском',LATE:'Не успеваем',DATA:'Нужно уточнить данные'};
const money=(value:number)=>value.toLocaleString('ru-RU',{style:'currency',currency:'RUB',maximumFractionDigits:2});
export function ForecastAttention({revision,refresh,onOpen}:{revision:number;refresh:number;onOpen:(id:string)=>void}){
 const [selected,setSelected]=useState<Filter|null>(null),[page,setPage]=useState(1),[report,setReport]=useState<(Report&{filter:Filter})|null>(null),[error,setError]=useState(''),[loading,setLoading]=useState(true);
 const filter=selected??'RISK';
 useEffect(()=>{let active=true;setLoading(true);const timer=setTimeout(()=>{api<Report>(`/planner/forecast-attention?filter=${filter}&page=${page}`).then(data=>{if(active){setReport({...data,filter});setError('');}}).catch(e=>{if(active)setError(e.message);}).finally(()=>{if(active)setLoading(false);});},250);return()=>{active=false;clearTimeout(timer);};},[filter,page,revision,refresh]);
 return <section className="forecast-attention" aria-label="Риски заказов"><h3>Требуют внимания</h3>{error&&<p className="error" role="alert">{error}</p>}<div className="dispatcher-metrics">{(Object.keys(labels) as Filter[]).map(key=><button key={key} aria-pressed={selected===key} className={`${selected===key?'selected':''} ${key==='DATA'?'':'danger'}`} onClick={()=>{setSelected(key);setPage(1);}}><span>{labels[key]}</span><strong>{report?`${report.counts[key].count} заказов`:'Расчёт…'}</strong><b>{report?money(report.counts[key].amount):'—'}</b></button>)}</div><p className="dispatcher-note">Стоимость незавершённой части заказа. Эти выборки пересекаются с производственными стадиями, суммы не складываются. Нажмите показатель, чтобы открыть список.</p>{selected&&<section className="panel dispatcher-orders"><h3>{labels[selected]}</h3>{loading||report?.filter!==selected||report?.page!==page?<p>Расчёт выборки…</p>:!report.items.length?<p>В этой выборке заказов нет</p>:report.items.map(row=><button key={row.id} onClick={()=>onOpen(row.id)}><span><strong>Производство № {row.number}</strong><small className="forecast-reason">{row.reason}</small></span><span>{row.finish?`Прогноз: ${new Date(row.finish).toLocaleString('ru-RU')}`:'Прогноз пока недоступен'}{row.dueDate&&<small className="forecast-reason">Срок: {new Date(row.dueDate).toLocaleDateString('ru-RU')}</small>}</span><b>{money(row.amount)}</b></button>)}<div className="pagination"><button className="secondary" disabled={loading||page===1} onClick={()=>setPage(p=>p-1)}>Предыдущие заказы</button><span>Страница {page} из {Math.max(1,Math.ceil((report?.total??0)/30))}</span><button className="secondary" disabled={loading||!report||page*30>=report.total} onClick={()=>setPage(p=>p+1)}>Следующие заказы</button></div></section>}</section>;
}
