import {RemainingPlan} from "./remaining-plan";
import {useEffect,useState} from 'react';
import {productionApi as api,useProductionEvents} from './production-api';
type Report={finish:string|null;reserveHours:number|null;state:string;dueDate:string|null;riskHours:number|null;updatedAt:string;asOf:string;reasons:string[];items:{id:string;name:string;remaining:number;plannedRemaining:boolean;completed:boolean;finish:string|null;reasons:string[]}[];procurement:{status:string;expectedAt:string|null}|null;continuousCenters:string[];unlimitedCenters:string[]};
const labels:Record<string,string>={COMPLETED:'Завершено',UNKNOWN:'Недостаточно данных',NO_DEADLINE:'Срок не задан',NO_THRESHOLD:'Порог риска не задан',LATE:'НЕ УСПЕВАЕМ',RISK:'РИСК',ON_TIME:'УСПЕВАЕМ'};
const date=(value:string|null)=>value?new Date(value).toLocaleString('ru-RU'):'Не задано';
export function OrderForecast({id}:{id:string}){
  const [planning,setPlanning]=useState<{id:string;name:string}|null>(null);
  const [draftVersion,setDraftVersion]=useState("");
  const [report,setReport]=useState<Report|null>(null),[risk,setRisk]=useState<number|''>(''),[error,setError]=useState(''),[busy,setBusy]=useState(false),[refresh,setRefresh]=useState(0),[dirty,setDirty]=useState(false);
  const revision=useProductionEvents();
  useEffect(()=>{let active=true;api<Report>(`/orders/${id}/forecast`).then(next=>{if(active){setReport(next);setError('');if(!dirty)setRisk(next.riskHours??'');}}).catch(e=>{if(active)setError(e.message);});return()=>{active=false;};},[id,revision,refresh,dirty]);
  async function save(){if(!report||busy)return;setBusy(true);setError('');try{await api(`/orders/${id}/forecast-settings`,{method:'PATCH',body:JSON.stringify({riskHours:risk===''?null:risk,updatedAt:draftVersion})});setDirty(false);setRefresh(v=>v+1);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
  return <section aria-label="Прогноз заказа"><h3>Прогноз заказа</h3><button className="secondary" disabled={busy} onClick={()=>{setDirty(false);setRefresh(v=>v+1);}}>Обновить прогноз</button>{error&&<p role="alert" className="error">{error}</p>}{!report?<p>Расчёт…</p>:<><p><strong>{labels[report.state]}</strong></p><p>Срок заказа: {report.dueDate?new Date(report.dueDate).toLocaleDateString("ru-RU"):"Не задан"}</p>{report.finish&&<p>Прогноз завершения: {date(report.finish)}</p>}{report.reserveHours!==null&&<p>{report.reserveHours<0?'Отклонение':'Резерв'}: {Math.abs(report.reserveHours).toLocaleString('ru-RU',{maximumFractionDigits:1})} ч</p>}{report.procurement&&!['READY','NOT_REQUIRED'].includes(report.procurement.status)&&<p>Ожидаем закупку: {date(report.procurement.expectedAt)}</p>}{report.items.map(item=><div className="dispatcher-item" key={item.id}><b>{item.name}</b><span>{item.completed?'Готово':item.finish?`Прогноз: ${date(item.finish)}`:'Дата пока не определена'}</span>{item.reasons.length>0&&<ul>{item.reasons.map(reason=><li key={reason}>{reason}</li>)}</ul>}{item.remaining>0&&<><span>Остаток: {item.remaining} шт.{item.plannedRemaining?" · учтён предварительный план":""}</span><button className="secondary" onClick={()=>setPlanning({id:item.id,name:item.name})}>{item.plannedRemaining?"Изменить план остатка":"Спланировать остаток"}</button></>}</div>)}{!report.items.length&&<p>В заказе нет позиций.</p>}<form onSubmit={e=>{e.preventDefault();void save();}}><label>Порог риска заказа, ч<input type="number" min="0" max="100000" step="any" value={risk} onChange={e=>{if(!dirty)setDraftVersion(report.updatedAt);setDirty(true);setRisk(e.target.value===''?'':Number(e.target.value));}}/></label><button className="secondary" disabled={busy||!dirty}>{busy?'Сохраняю…':'Сохранить порог риска'}</button></form><p><small>Резерв указан в календарных часах, срок без времени — до конца даты UTC. Расчёт учитывает задачи других заказов, смены и ожидаемую готовность закупки для ещё не начатых задач. Дата закупки — плановая: прогноз зависит от её соблюдения. Незапущенное количество без плана блокирует итоговую дату.</small></p>{report.continuousCenters.length>0&&<p><small>Без календаря (24/7): {report.continuousCenters.join(', ')}.</small></p>}{report.unlimitedCenters.length>0&&<p><small>Вместимость не задана: {report.unlimitedCenters.join(', ')}.</small></p>}</>}{planning&&<RemainingPlan id={planning.id} name={planning.name} onClose={()=>setPlanning(null)} onSaved={()=>{setPlanning(null);setRefresh(v=>v+1);}}/>}</section>;
}
