import {useEffect,useState} from 'react';
import {productionApi as api} from './production-api';
type Plan={routeId:string;start:string|null;steps:{stepId:string;hoursPerUnit:number}[]};
type Data={plan:Plan|null;version:number;remaining:number;routes:{id:string;name:string;version:number;steps:{id:string;title:string;workCenter:{name:string}}[]}[]};
const local=(value:string|null)=>value?new Date(Date.parse(value)-new Date(value).getTimezoneOffset()*60000).toISOString().slice(0,16):'';
export function RemainingPlan({id,name,onClose,onSaved}:{id:string;name:string;onClose:()=>void;onSaved:()=>void}){
 const [data,setData]=useState<Data|null>(null),[routeId,setRouteId]=useState(''),[start,setStart]=useState(''),[norms,setNorms]=useState<Record<string,number|''>>({}),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 useEffect(()=>{let active=true;api<Data>(`/order-items/${id}/remaining-plan`).then(d=>{if(!active)return;setData(d);setRouteId(d.plan?.routeId??'');setStart(local(d.plan?.start??null));setNorms(Object.fromEntries(d.plan?.steps.map(s=>[s.stepId,s.hoursPerUnit])??[]));}).catch(e=>{if(active)setError(e.message);});return()=>{active=false;};},[id]);
 const route=data?.routes.find(r=>r.id===routeId);
 async function save(clear=false){if(!data||busy)return;setError('');if(!clear&&(!route||!route.steps.length||route.steps.some(s=>!norms[s.id]))){setError('Выберите маршрут и заполните норматив каждого этапа');return;}setBusy(true);try{await api(`/order-items/${id}/remaining-plan`,{method:'PUT',body:JSON.stringify({version:data.version,plan:clear?null:{routeId,start:start?new Date(start).toISOString():null,steps:route!.steps.map(s=>({stepId:s.id,hoursPerUnit:norms[s.id]}))}})});onSaved();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <div className="modal-backdrop action-backdrop"><form className="task-dialog" role="dialog" aria-modal="true" aria-label="План незапущенного остатка" onSubmit={e=>{e.preventDefault();void save();}}><header><h2>План остатка: {name}</h2><button type="button" disabled={busy} aria-label="Закрыть план остатка" onClick={onClose}>×</button></header>{error&&<p role="alert" className="error">{error}</p>}{!data?<p>Загрузка…</p>:<><p>Не запущено: {data.remaining} шт. Норматив на одно изделие умножается на оставшееся количество.</p><label>Маршрут остатка<select aria-label="Маршрут остатка" required value={routeId} onChange={e=>{setRouteId(e.target.value);setNorms({});}}><option value="">Выберите сохранённый маршрут</option>{data.routes.map(r=><option key={r.id} value={r.id}>{r.name} · версия {r.version}</option>)}</select></label>{!data.routes.length&&<p>Сначала создайте технологический маршрут позиции в разделе «Запуски».</p>}<label>Предполагаемое начало<input type="datetime-local" value={start} onChange={e=>setStart(e.target.value)}/></label><p>Пустая дата — ближайшее доступное время с учётом закупки и загрузки. Время указано в часовом поясе компьютера.</p>{route?.steps.map((step,index)=><label key={step.id}>{index+1}. {step.workCenter.name} · {step.title}<input aria-label={`Норматив этапа ${index+1}, ч на изделие`} required type="number" min="0.000001" step="any" max={100000/Math.max(1,data.remaining)} value={norms[step.id]??''} onChange={e=>setNorms(n=>({...n,[step.id]:e.target.value===''?'':Number(e.target.value)}))}/></label>)}<p>Это предварительный расчёт выбранной версии маршрута. План не создаёт запуск и не резервирует места. Незапущенные планы других заказов пока не учитываются. При частичном запуске расчёт автоматически уменьшает остаток. При запуске по этой версии маршрута нормативы переносятся в задачи.</p><footer>{data.plan&&<button type="button" className="secondary" disabled={busy} onClick={()=>void save(true)}>Убрать план остатка</button>}<button type="button" className="secondary" disabled={busy} onClick={onClose}>Отмена</button><button className="primary" disabled={busy||!data.remaining||!route}>{busy?'Сохраняю…':'Сохранить план остатка'}</button></footer></>}</form></div>;
}
