import { lazy, Suspense, useEffect, useState } from "react";
import { Archive, Copy, Pencil, Route, Trash2 } from "lucide-react";
import { productionApi as api } from "./production-api";
import type { ProductionRoute } from "./route-graph";
import "./route-templates.css";

type Template={id:string;name:string;description?:string|null;category?:string|null;archivedAt?:string|null;updatedAt:string;author:{firstName:string;lastName:string};steps:{id:string;title:string;material?:string|null;workCenter:{name:string};predecessors:{predecessorId:string}[]}[]};
type Center={id:string;name:string};
const RouteBuilder=lazy(()=>import("./route-graph").then(module=>({default:module.RouteBuilder})));

export function RouteTemplates(){
  const [templates,setTemplates]=useState<Template[]>([]),[search,setSearch]=useState(""),[archived,setArchived]=useState(false),[loading,setLoading]=useState(true),[busy,setBusy]=useState(""),[error,setError]=useState(""),[centers,setCenters]=useState<Center[]>([]),[editing,setEditing]=useState<Template|null>(null);
  const load=async()=>{setLoading(true);try{setTemplates(await api<Template[]>(`/route-templates?archived=${archived?"true":"false"}&search=${encodeURIComponent(search)}`));setError("");}catch(error){setError(error instanceof Error?error.message:"Не удалось загрузить шаблоны");}finally{setLoading(false);}};
  useEffect(()=>{const timer=setTimeout(()=>void load(),180);return()=>clearTimeout(timer);},[search,archived]);
  useEffect(()=>{void api<Center[]>("/work-centers").then(setCenters).catch(()=>{});},[]);
  async function copy(template:Template){const name=window.prompt("Название копии шаблона",`${template.name} — копия`);if(!name?.trim())return;setBusy(template.id);try{await api(`/route-templates/${template.id}/copy`,{method:"POST",body:JSON.stringify({name:name.trim()})});await load();}catch(error){setError(error instanceof Error?error.message:"Не удалось скопировать шаблон");}finally{setBusy("");}}
  async function setArchive(template:Template,value:boolean){setBusy(template.id);try{await api(`/route-templates/${template.id}/archive`,{method:"PATCH",body:JSON.stringify({archived:value})});await load();}catch(error){setError(error instanceof Error?error.message:"Не удалось изменить архив");}finally{setBusy("");}}
  async function remove(template:Template){if(!window.confirm(`Удалить шаблон «${template.name}»? Использованный шаблон будет перенесён в архив.`))return;setBusy(template.id);try{await api(`/route-templates/${template.id}`,{method:"DELETE"});await load();}catch(error){setError(error instanceof Error?error.message:"Не удалось удалить шаблон");}finally{setBusy("");}}
  return <section className="content template-library"><div className="page-actions"><div><p className="kicker">ТЕХНОЛОГИЧЕСКИЕ МАРШРУТЫ</p><h2>Шаблоны маршрутов</h2><p>Создайте маршрут в «Запусках» и сохраните его как шаблон. Здесь можно найти и подготовить его для повторного применения.</p></div><div><input aria-label="Поиск шаблонов" placeholder="Найти шаблон" value={search} onChange={event=>setSearch(event.target.value)}/><button className="secondary" onClick={()=>setArchived(value=>!value)}>{archived?"Активные шаблоны":"Архив шаблонов"}</button></div></div>{error&&<div className="planning-error" role="alert">{error}</div>}{loading?<p>Загрузка шаблонов…</p>:<div className="template-grid">{templates.map(template=><article key={template.id}><header><div><Route/><div><b>{template.name}</b><small>{template.category||"Без категории"} · {template.steps.length} этапов</small></div></div><time dateTime={template.updatedAt}>Изменён {new Date(template.updatedAt).toLocaleDateString("ru-RU")}</time></header>{template.description&&<p>{template.description}</p>}<ol>{template.steps.map(step=><li key={step.id}><span>{step.workCenter.name}</span><b>{step.title}</b>{step.material&&<small>{step.material.split("\n").filter(Boolean).join(" · ")}</small>}{step.predecessors.length>1&&<em>объединяет {step.predecessors.length} ветви</em>}</li>)}</ol><footer><button disabled={!!busy||!centers.length||archived} onClick={()=>setEditing(template)}><Pencil/>Изменить</button><button disabled={!!busy} onClick={()=>void copy(template)}><Copy/>Копировать</button>{archived?<button disabled={!!busy} onClick={()=>void setArchive(template,false)}>Восстановить</button>:<button disabled={!!busy} onClick={()=>void setArchive(template,true)}><Archive/>В архив</button>}<button className="danger" disabled={!!busy} onClick={()=>void remove(template)}><Trash2/>Удалить</button></footer></article>)}{!templates.length&&<div className="template-empty"><Route/><b>{archived?"В архиве нет шаблонов":"Шаблонов пока нет"}</b><span>Сохраните готовый маршрут из конструктора, чтобы использовать его в других запусках.</span></div>}</div>}{editing&&<Suspense fallback={<div className="modal-backdrop"><div className="task-dialog"><p>Открываю конструктор шаблона…</p></div></div>}><RouteBuilder item={{id:editing.id,name:editing.name}} centers={centers} initial={editing as unknown as ProductionRoute} templateId={editing.id} templateMeta={{description:editing.description,category:editing.category}} onClose={()=>setEditing(null)} onSaved={()=>{setEditing(null);void load();}}/></Suspense>}</section>;
}
