import { useEffect, useState, type FormEvent } from "react";
import { productionApi as api } from "./production-api";
type Center = { id: string; name: string };
type Staff = { id: string; login: string; firstName: string; lastName: string; active: boolean; workCenters: { workCenter: Center }[] };
export function StaffScreen() {
  const [staff,setStaff]=useState<Staff[]>([]), [centers,setCenters]=useState<Center[]>([]), [editing,setEditing]=useState<Staff|null|undefined>(), [error,setError]=useState(""), [loading,setLoading]=useState(true), [search,setSearch]=useState("");
  async function load(){ try { const [people,sites]=await Promise.all([api<Staff[]>("/staff"),api<Center[]>("/work-centers")]);setStaff(people);setCenters(sites); }catch(e){setError(e instanceof Error?e.message:"Ошибка загрузки");}finally{setLoading(false);} }
  useEffect(()=>{void load();},[]);
  const filtered=staff.filter(p=>`${p.login} ${p.firstName} ${p.lastName}`.toLowerCase().includes(search.toLowerCase()));
  return <div className="content"><div className="page-actions"><div><p className="kicker">КОМАНДА</p><h2>Сотрудники участков</h2></div><button className="primary" onClick={()=>setEditing(null)}>Добавить сотрудника</button></div><label>Поиск по имени или логину<input value={search} onChange={e=>setSearch(e.target.value)}/></label>{error&&<p className="error" role="alert">{error}</p>}{loading?<p>Загрузка…</p>:filtered.length===0?<p>Сотрудников не найдено</p>:<div className="procurement-list">{filtered.map(p=><article className="procurement-card" key={p.id}><div><h3>{p.lastName} {p.firstName}</h3><span>{p.login}</span></div><div>{p.workCenters.map(c=>c.workCenter.name).join(", ")||"Участки не назначены"}</div><b>{p.active?"Доступ открыт":"Доступ отключён"}</b><button className="secondary" onClick={()=>setEditing(p)}>Изменить</button></article>)}</div>}{editing!==undefined&&<StaffForm key={editing?.id??"new"} person={editing} centers={centers} onClose={()=>setEditing(undefined)} onSaved={()=>{setEditing(undefined);void load();}}/>}</div>;
}
function StaffForm({person,centers,onClose,onSaved}:{person:Staff|null;centers:Center[];onClose:()=>void;onSaved:()=>void}) {
  const [login,setLogin]=useState(person?.login??""),[firstName,setFirstName]=useState(person?.firstName??""),[lastName,setLastName]=useState(person?.lastName??""),[password,setPassword]=useState(""),[active,setActive]=useState(person?.active??true),[ids,setIds]=useState(person?.workCenters.map(c=>c.workCenter.id)??[]),[error,setError]=useState(""),[busy,setBusy]=useState(false);
  async function submit(e:FormEvent){e.preventDefault();if(person?.active&&!active&&!window.confirm(`Отключить доступ сотрудника ${person.lastName} ${person.firstName}?`))return;setBusy(true);setError("");try{await api(`/staff${person?`/${person.id}`:""}`,{method:person?"PUT":"POST",body:JSON.stringify({login,firstName,lastName,active,workCenterIds:ids,...(password?{password}:{})})});setPassword("");onSaved();}catch(e){setError(e instanceof Error?e.message:"Не удалось сохранить");}finally{setBusy(false);}}
  return <div className="modal-backdrop"><form className="order-form" onSubmit={submit} role="dialog" aria-modal="true" aria-label="Учётная запись сотрудника"><div className="form-head"><h2>{person?"Изменить сотрудника":"Новый сотрудник"}</h2><button type="button" className="close" onClick={onClose} disabled={busy} aria-label="Закрыть">×</button></div><div className="form-grid"><label>Фамилия<input value={lastName} onChange={e=>setLastName(e.target.value)} required maxLength={100}/></label><label>Имя<input value={firstName} onChange={e=>setFirstName(e.target.value)} required maxLength={100}/></label><label>Логин<input value={login} onChange={e=>setLogin(e.target.value)} required maxLength={100} autoComplete="off"/></label><label>{person?"Новый пароль (оставьте пустым, чтобы сохранить текущий)":"Пароль"}<input type="password" value={password} onChange={e=>setPassword(e.target.value)} required={!person} minLength={10} maxLength={256} autoComplete="new-password"/></label></div><fieldset><legend>Участки сотрудника</legend>{centers.map(c=><label key={c.id} style={{display:"flex",alignItems:"center",gap:8,padding:6}}><input type="checkbox" style={{width:"auto"}} checked={ids.includes(c.id)} onChange={e=>setIds(e.target.checked?[...ids,c.id]:ids.filter(id=>id!==c.id))}/>{c.name}</label>)}</fieldset><label style={{display:"flex",gap:8,alignItems:"center"}}><input type="checkbox" style={{width:"auto"}} checked={active} onChange={e=>setActive(e.target.checked)}/>Доступ к системе открыт</label>{error&&<p className="error" role="alert">{error}</p>}<footer><button type="button" className="secondary" disabled={busy} onClick={onClose}>Отмена</button><button className="primary" disabled={busy}>{busy?"Сохранение…":"Сохранить"}</button></footer></form></div>;
}
