import {WorkCalendar} from "./work-calendar";
import {useEffect,useState} from 'react';
import {productionApi as api} from './production-api';
type Result={queueHours?:number;afterTask?:string;finish:string|null;reserveHours:number|null;state:string;reason?:string};
const labels:Record<string,string>={UNKNOWN:'Недостаточно данных',COMPLETED:'Завершено',NO_DEADLINE:'Срок не задан',NO_THRESHOLD:'Порог риска не задан',LATE:'НЕ УСПЕВАЕМ',RISK:'РИСК',ON_TIME:'УСПЕВАЕМ'};
export function TaskForecast({id,centerId,version,revision}:{id:string;centerId:string;version:number;revision:number}){
  const [unlimited,setUnlimited]=useState<string[]>([]);
  const [calendar,setCalendar]=useState(false),[refresh,setRefresh]=useState(0),[continuous,setContinuous]=useState<string[]>([]);
  const [result,setResult]=useState<Result|null>(null),[error,setError]=useState('');
  useEffect(()=>{let active=true;setResult(null);setError('');api<{stage:Result;continuousCenters:string[];unlimitedCenters:string[]}>(`/operations/${id}/forecast`).then(data=>{if(active){setResult(data.stage);setContinuous(data.continuousCenters);setUnlimited(data.unlimitedCenters);}}).catch(e=>{if(active)setError(e.message);});return()=>{active=false;};},[id,version,revision,refresh]);
  return <section aria-label="Прогноз этапа"><h3>Прогноз этапа</h3>{error?<p role="alert">{error}</p>:!result?<p>Расчёт…</p>:<><b>{labels[result.state]}</b>{result.reason&&<p>{result.reason}</p>}{result.finish&&result.state!=='COMPLETED'&&<p>Завершение: {new Date(result.finish).toLocaleString('ru-RU')}</p>}{result.reserveHours!==null&&<p>{result.reserveHours<0?'Отклонение':'Резерв'}: {Math.abs(result.reserveHours).toLocaleString('ru-RU',{maximumFractionDigits:1})} ч</p>}{(result.queueHours??0)>0&&<p>Ожидание очереди: {result.queueHours!.toLocaleString("ru-RU",{maximumFractionDigits:1})} ч{result.afterTask?` · после «${result.afterTask}»`:""}</p>}</>}<small>Расчёт по оставшемуся нормативу, связям маршрута и заданным сменам. Резерв указан в календарных часах. Учитываются другие активные задачи, порядок очереди и число одновременно выполняемых задач. Уже начатые задачи имеют преимущество.</small>{result&&continuous.length>0&&<p>Без рабочего календаря (расчёт 24/7): {continuous.join(", ")}.</p>}{result&&unlimited.length>0&&<p>Загрузка не ограничена (вместимость не задана): {unlimited.join(", ")}.</p>}<p><button className="secondary" onClick={()=>setCalendar(true)}>Рабочий календарь участка</button></p>{calendar&&<WorkCalendar id={centerId} onClose={()=>setCalendar(false)} onSaved={()=>{setCalendar(false);setRefresh(v=>v+1);}}/>}</section>;
}
