import {useEffect,useState} from 'react';
import {productionApi as api} from './production-api';
type Calendar={utcOffsetMinutes:number;shifts:{day:number;start:number;end:number}[];holidays:string[]};
type Center={parallelSlots:number|null;name:string;calendar:Calendar|null;calendarVersion:number};
const days=['Вс','Пн','Вт','Ср','Чт','Пт','Сб'];
const time=(minutes:number)=>`${String(Math.floor(minutes/60)).padStart(2,'0')}:${String(minutes%60).padStart(2,'0')}`;
const minutes=(value:string)=>{const [h,m]=value.split(':').map(Number);return h*60+m;};
export function WorkCalendar({id,onClose,onSaved}:{id:string;onClose:()=>void;onSaved:()=>void}){
  const [capacity,setCapacity]=useState<number|"">("");
  const [center,setCenter]=useState<Center|null>(null),[enabled,setEnabled]=useState(false),[offset,setOffset]=useState<number|''>(''),[shifts,setShifts]=useState<Calendar['shifts']>([]),[holidays,setHolidays]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('');
  useEffect(()=>{let active=true;api<Center>(`/work-centers/${id}/calendar`).then(c=>{if(!active)return;setCenter(c);setCapacity(c.parallelSlots??"");setEnabled(!!c.calendar);setOffset(c.calendar?c.calendar.utcOffsetMinutes/60:'');setShifts(c.calendar?.shifts??[]);setHolidays(c.calendar?.holidays.join('\n')??'');}).catch(e=>{if(active)setError(e.message);});return()=>{active=false;};},[id]);
  async function save(){if(!center||busy)return;setError('');if(enabled&&(offset===''||!shifts.length)){setError('Укажите часовой пояс и добавьте смены');return;}setBusy(true);try{await api(`/work-centers/${id}/calendar`,{method:'PUT',body:JSON.stringify({calendarVersion:center.calendarVersion,parallelSlots:capacity===""?null:capacity,calendar:enabled?{utcOffsetMinutes:Number(offset)*60,shifts,holidays:holidays.split(/\s+/).filter(Boolean)}:null})});onSaved();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
  return <div className="modal-backdrop action-backdrop"><form className="task-dialog" role="dialog" aria-modal="true" aria-label="Рабочий календарь" onSubmit={e=>{e.preventDefault();void save();}}><header><h2>Календарь: {center?.name??'загрузка…'}</h2><button type="button" aria-label="Закрыть календарь" disabled={busy} onClick={onClose}>×</button></header>{error&&<p role="alert" className="planning-error">{error}</p>}{center&&<><label>Одновременно выполняемых задач<input type="number" min="1" max="100" step="1" value={capacity} onChange={e=>setCapacity(e.target.value===""?"":Number(e.target.value))}/></label><p>Укажите реальную вместимость участка. Пустое поле — ограничение загрузки не учитывается.</p><label><input type="checkbox" checked={enabled} onChange={e=>setEnabled(e.target.checked)}/>Учитывать рабочие смены</label><p>Настройка применяется ко всем задачам этого участка. Она меняет прогноз, но не ограничивает начало и завершение работы сотрудником.</p>{enabled&&<><label>Смещение от UTC, ч<input type="number" required min="-12" max="14" step="0.25" placeholder="Например, 3 для Москвы" value={offset} onChange={e=>setOffset(e.target.value===''?'':Number(e.target.value))}/></label><p>Время смен указано в этом часовом поясе. Сезонный перевод часов не выполняется.</p>{shifts.map((shift,i)=><fieldset key={i}><legend>Смена {i+1}</legend><label>День недели<select value={shift.day} onChange={e=>setShifts(rows=>rows.map((s,j)=>i===j?{...s,day:Number(e.target.value)}:s))}>{days.map((day,index)=><option key={day} value={index}>{day}</option>)}</select></label><label>Начало<input type="time" required value={time(shift.start)} onChange={e=>setShifts(rows=>rows.map((s,j)=>i===j?{...s,start:minutes(e.target.value)}:s))}/></label><label>Конец<input type="time" required value={time(shift.end===1440?0:shift.end)} onChange={e=>setShifts(rows=>rows.map((s,j)=>i===j?{...s,end:minutes(e.target.value)||1440}:s))}/></label><button type="button" className="secondary" onClick={()=>setShifts(rows=>rows.filter((_,j)=>i!==j))}>Удалить смену {i+1}</button></fieldset>)}<button type="button" className="secondary" disabled={shifts.length>=28} onClick={()=>setShifts(rows=>[...rows,{day:1,start:540,end:1080}])}>Добавить смену</button><p>Проверьте время добавленной смены. Для перерыва добавьте два интервала, для ночной смены — интервалы до 00:00 и после 00:00 следующего дня.</p><label>Выходные даты<textarea aria-label="Выходные даты" placeholder={'2026-12-31\n2027-01-01'} value={holidays} onChange={e=>setHolidays(e.target.value)}/></label><p>По одной дате ГГГГ-ММ-ДД на строку. Праздники автоматически не добавляются.</p></>}<footer><button type="button" className="secondary" disabled={busy} onClick={onClose}>Отмена</button><button className="primary" disabled={busy}>{busy?'Сохраняю…':'Сохранить календарь'}</button></footer></>}</form></div>;
}
