ALTER TABLE "Operation"
ADD COLUMN "plannedStart" TIMESTAMP(3),
ADD COLUMN "plannedFinish" TIMESTAMP(3),
ADD COLUMN "queueOrder" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN "planVersion" INTEGER NOT NULL DEFAULT 0;
